Update tv1 all tests ok, ne proshel proverky
При запуске все тесты ок, выдает:

TestExcludeStopWordsFromAddedDocumentContent OK

TestFindAddedDocumentByDocumentWord OK

TestExcludeDocumentsWithMinusWordsFromResults OK

TestMatchedDocuments OK

TestSortResultsByRelevance OK

TestCalculateDocumentRating OK

TestDocumentSearchByPredicate OK

TestDocumentSearchByStatus OK

TestCalculateRelevance OK

Search server testing finished


При проверке выдает:

/tmp/framework/search_server.h:257:29: error: loop variable ‘<structured bindings>’ creates a copy from type ‘const std::pair<const int, double>’ [-Werror=range-loop-construct]

  257 |             for (const auto [document_id, term_freq] : word_to_document_freqs_.at(word)) {

      |                             ^~~~~~~~~~~~~~~~~~~~~~~~

/tmp/framework/search_server.h:257:29: note: use reference type to prevent copying

  257 |             for (const auto [document_id, term_freq] : word_to_document_freqs_.at(word)) {

      |                             ^~~~~~~~~~~~~~~~~~~~~~~~

      |                             &

/tmp/framework/search_server.h:287:29: error: loop variable ‘<structured bindings>’ creates a copy from type ‘const std::pair<const int, double>’ [-Werror=range-loop-construct]

  287 |             for (const auto [document_id, _] : word_to_document_freqs_.at(word)) {

      |                             ^~~~~~~~~~~~~~~~

/tmp/framework/search_server.h:287:29: note: use reference type to prevent copying

  287 |             for (const auto [document_id, _] : word_to_document_freqs_.at(word)) {

      |                             ^~~~~~~~~~~~~~~~

      |                             &

/tmp/framework/search_server.h:293:25: error: loop variable ‘<structured bindings>’ creates a copy from type ‘const std::pair<const int, double>’ [-Werror=range-loop-construct]

  293 |         for (const auto [document_id, relevance] : document_to_relevance) {

      |                         ^~~~~~~~~~~~~~~~~~~~~~~~

/tmp/framework/search_server.h:293:25: note: use reference type to prevent copying

  293 |         for (const auto [document_id, relevance] : document_to_relevance) {

      |                         ^~~~~~~~~~~~~~~~~~~~~~~~

      |                         &

/tmp/framework/search_server.h: In instantiation of ‘std::vector<Document> SearchServer::FindAllDocuments(const Query&, DocumentPredicate) const [with DocumentPredicate = TestDocumentSearchByPredicate()::<lambda(int, DocumentStatus, int)>]’:

/tmp/framework/search_server.h:72:50:   required from ‘std::vector<Document> SearchServer::FindTopDocuments(const std::string&, DocumentPredicate) const [with DocumentPredicate = TestDocumentSearchByPredicate()::<lambda(int, DocumentStatus, int)>; std::string = std::__cxx11::basic_string<char>]’

/tmp/tmpnmcjv447/main.cpp:477:52:   required from here

/tmp/framework/search_server.h:257:29: error: loop variable ‘<structured bindings>’ creates a copy from type ‘const std::pair<const int, double>’ [-Werror=range-loop-construct]

  257 |             for (const auto [document_id, term_freq] : word_to_document_freqs_.at(word)) {

      |                             ^~~~~~~~~~~~~~~~~~~~~~~~

/tmp/framework/search_server.h:257:29: note: use reference type to prevent copying

  257 |             for (const auto [document_id, term_freq] : word_to_document_freqs_.at(word)) {

      |                             ^~~~~~~~~~~~~~~~~~~~~~~~

      |                             &

/tmp/framework/search_server.h:287:29: error: loop variable ‘<structured bindings>’ creates a copy from type ‘const std::pair<const int, double>’ [-Werror=range-loop-construct]

  287 |             for (const auto [document_id, _] : word_to_document_freqs_.at(word)) {

      |                             ^~~~~~~~~~~~~~~~

/tmp/framework/search_server.h:287:29: note: use reference type to prevent copying

  287 |             for (const auto [document_id, _] : word_to_document_freqs_.at(word)) {

      |                             ^~~~~~~~~~~~~~~~

      |                             &

/tmp/framework/search_server.h:293:25: error: loop variable ‘<structured bindings>’ creates a copy from type ‘const std::pair<const int, double>’ [-Werror=range-loop-construct]

  293 |         for (const auto [document_id, relevance] : document_to_relevance) {

      |                         ^~~~~~~~~~~~~~~~~~~~~~~~

/tmp/framework/search_server.h:293:25: note: use reference type to prevent copying

  293 |         for (const auto [document_id, relevance] : document_to_relevance) {

      |                         ^~~~~~~~~~~~~~~~~~~~~~~~

      |                         &

cc1plus: all warnings being treated as errors

Требует добавить ссылку в 257, 287, 293 строке, в чем подвох?